### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by dacom-dark-sun** [gxchain/gxb-core#10]
Compilation problem detected on macos. What reason can be? 

[ 83%] Linking CXX executable embed_genesis
Undefined symbols for architecture x86_64:
  "graphene::chain::database::add_checkpoints(boost::container::flat_map<unsigned int, fc::ripemd160, std::__1::less<unsigned int>, boost::container::new_allocator<std::__1::pair<unsigned int, fc::ripemd160> > > const&)", referenced from:
      graphene::app::detail::application_impl::startup() in libgraphene_app.a(application.cpp.o)
  "graphene::chain::signed_transaction::get_required_signatures(fc::sha256 const&, boost::container::flat_set<graphene::chain::public_key_type, std::__1::less<graphene::chain::public_key_type>, boost::container::new_allocator<graphene::chain::public_key_type> > const&, std::__1::function<graphene::chain::authority const* (graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>)> const&, std::__1::function<graphene::chain::authority const* (graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>)> const&, unsigned int) const", referenced from:
      graphene::app::database_api_impl::get_required_signatures(graphene::chain::signed_transaction const&, boost::container::flat_set<graphene::chain::public_key_type, std::__1::less<graphene::chain::public_key_type>, boost::container::new_allocator<graphene::chain::public_key_type> > const&) const in libgraphene_app.a(database_api_impl.cpp.o)
      graphene::app::database_api_impl::get_potential_signatures(graphene::chain::signed_transaction const&) const in libgraphene_app.a(database_api_impl.cpp.o)
      graphene::app::database_api_impl::get_potential_address_signatures(graphene::chain::signed_transaction const&) const in libgraphene_app.a(database_api_impl.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libraries/egenesis/embed_genesis] Error 1
make[1]: *** [libraries/egenesis/CMakeFiles/embed_genesis.dir/all] Error 2
make: *** [all] Error 2

**Comment by tututt** [comment]
Please try to update your clang to version9.0

**Comment by tututt** [comment]
the version of clang is too old ,that can cause this error.
