### ISSUE TITLE
Start private chain failed

### ISSUE THREAD

**Issue by viettienbk** [gxchain/gxb-core#111]
**Describe the bug**
I follow the instructions in this article to start privatechain, but it failed: https://docs.gxchain.org/guide/private_chain.html

**Screenshots**
![screen shot 2019-01-10 at 14 45 05](https://user-images.githubusercontent.com/13216663/50953588-73d6c780-14e6-11e9-9de5-8ae036d0fe80.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version: GXB-Core Release v1.0.181226

**Comment by zhuliting** [comment]
@viettienbk 

please use branch private-net to run private net,  or download package:
```
curl 'https://raw.githubusercontent.com/gxchain/gxb-core/dev_master/script/gxchain_private_net_install.sh' | bash
```

**Comment by viettienbk** [comment]
@zhuliting : It worked. Thank you very much.
