### ISSUE TITLE
How to register an account on private chain?

### ISSUE THREAD

**Issue by viettienbk** [gxchain/gxb-core#113]
I have successfully installed private network. Now, I want to transfer coin, but I dont know account_id or account_name.
So, how do I register a account via JSON-RPC on private network?

**Comment by zhuliting** [comment]
@viettienbk 
https://docs.gxchain.org/guide/private_chain.html#_3-create-an-account

**Comment by viettienbk** [comment]
thank @zhuliting . 
The doc need to update:
`register_account alpha GXC6vQtDEgHSickqe9itW8fbFyUrKZK5xsg4FRHzQZ7hStaWqEKhZ GXC6vQtDEgHSickqe9itW8fbFyUrKZK5xsg4FRHzQZ7hStaWqEKhZ nathan nathan 10`
to
`register_account alpha GXC6vQtDEgHSickqe9itW8fbFyUrKZK5xsg4FRHzQZ7hStaWqEKhZ GXC6vQtDEgHSickqe9itW8fbFyUrKZK5xsg4FRHzQZ7hStaWqEKhZ nathan nathan 10 true`
