### ISSUE TITLE
安卓app没有账户的数字id

### ISSUE THREAD

**Issue by tyhtao1990** [gxchain/gxb-core#12]
初学者入门，按照教程使用witness_node时，使用安卓app找了半天没有发现有数字账号。这个和文档里面的说明不符，后来从网页上重新注册了一个钱包才有数字账户
希望能够对app改进

**Comment by lanhaoxiang** [comment]
感谢你的建议，我们近期会对移动钱包加上account_id
这个属于核心模块，建议这个问题移动到gxs-wallet下
