### ISSUE TITLE
query the transaction with txid

### ISSUE THREAD

**Issue by zhuliting** [gxchain/gxb-core#139]
qurey the rawtransaction with  TXID

witness_node add command line option:
```
 -txindex
       Maintain a full transaction index, used by the getrawtransaction rpc call (default: false)
```

DB API:
request:
```
curl --data '{"jsonrpc": "2.0", "method": "call", "params": [0, "getrawtransaction", ["9e237106f2ccb7681692a25e1e57a45e5708e58b"]], "id": 1}' http://127.0.0.1:28090
```

response:
```
{
    "id":1,
    "jsonrpc":"2.0",
    "result":[
        {
            "ref_block_num":56074,
            "ref_block_prefix":950252836,
            "expiration":"2019-02-27T15:32:30",
            "operations":[
                [
                    0,
                    {
                        "fee":{
                            "amount":1210,
                            "asset_id":"1.3.1"
                        },
                        "from":"1.2.19643",
                        "to":"1.2.688063",
                        "amount":{
                            "amount":59970000,
                            "asset_id":"1.3.1"
                        },
                        "memo":{
                            "from":"GXC5XVSDA5R2mrHJFnKpkn7KTtQKcDTyUxES6KZ5tPWCVk9xEYdiB",
                            "to":"GXC7KaX3ANpuENYHtqE5yeH8dHWPiv6HvqyCLhDWH7fow9i6Pm2q9",
                            "nonce":"8792577754148118047",
                            "message":"847fd838d7d557348198aa18de7c801ec95352ac7f3cf09948ed422f78e63985"
                        },
                        "extensions":[

                        ]
                    }
                ]
            ],
            "extensions":[

            ],
            "signatures":[
                "2074416d6889cf1f20a4c6ab68322a10784d06917752aac3a613c3b4a603be48ee0785d42211f16df607049fab2052334e88d47d85819e9b10e5857861a43ee08d"
            ],
            "operation_results":[
                [
                    0,
                    {

                    }
                ]
            ]
        }
    ]
}
```

**Comment by RootkitKiller** [comment]
考虑了三种方案如下：
定义Tx_Index_Entry结构：
```
struct Tx_Index_Entry{
      transaction_id_type  txid;     //交易id/索引
      uint64_t          block_num;    //交易所在区块
      uint64_t          idx;        //交易为该区块的第几笔交易
} // 该结构共36字节
```
根据txid，获取所在区块，获取raw_block数据，再获取block中的transaction并返回。

主网目前有7千万笔交易。
方案1：将索引保存到内存中：7千万 * 36字节 = 21亿字节 = 2G内存，使用map容器保存。（apply_block时把索引写入文件，启动或重启witness_node时，load交易索引数据到内存中。）

方案2：索引仅保存在文件中，由于txid是无序的，无序查询一次，需要进行7千万次比较（7千万比交易），而且还没有考虑IO时间。get_block_by_id 接口可以通过block_num定位可以到索引文件中的位置。不考虑此方案

方案3：使用db来保存索引数据，减少内存占用的同时，增加查询的速度。

**Comment by lanhaoxiang** [comment]
@RootkitKiller  个人觉得方案1和方案3都可以考虑，方案3可以考虑引入leveldb；要分析引入难度和引入的风险和成本

**Comment by RootkitKiller** [comment]
查看了一下steem的实现方式，方案如下：

1、存在一个account_history_plugin插件，保存operation历史。比我们的插件对象，多了一个trx_id字段（保存了op关联的交易id），并定义了一个by_transaction_id的索引。

2、wallet_api（客户端）存在接口`get_transaction(txid)`，调用节点程序中的接口实现

`wallet_api::get_transaction（钱包客户端）`----->`condenser_api_impl::get_transaction（节点程序，验证插件是否开启）`------->`account_history_api::get_transaction（实现部分，插件提供的api）`

实现方式：通过by_transaction_id索引，在内存对象中找到txid相关的op_histroy对象，对象中保存了`block_num`和`trx_in_block`信息，然后从磁盘中取出transaction结构。

3、内存对象保存的条数？ steem是配置了tracked_account 范围，  指定了需要跟踪的账户。

总结：txid放在了内存对象中，与account_history_plugin插件合在一起，可以配置跟踪哪些账户相关的txid。

**Comment by RootkitKiller** [comment]
对方案3引入leveldb方案做一些补充，大概内容如下：

1、采用`内存对象+leveldb`的方案来保存`Tx_Index_Entry`结构。

* 对于可逆区块中的交易：一旦区块回滚，块中的交易会被丢弃。由于`graphene`提供的内置db，可以保证所有内存对象能够回滚，所以将这些交易保存在内存对象中。

* 对于不可逆区块中的交易：一旦交易所在区块被最终确认，则使用`leveldb`来代替内存对象存储，以此来减少内存占用。具体方式为：在响应不可逆区块信号时，将所有最终确认的交易写入到`leveldb`，并从内存对象中删掉。

2、crash的影响

由于将对象写入`leveldb`和删掉内存对象，需要保证它们的一致性。如果在此过程中机器crash，容易导致某些对象没有插入到数据库，但已经从内存中删掉，造成数据的丢失。参考了一些网络上的方案，决定采用同步写入来避免异步过程中机器crash的问题，批量插入来减弱同步写入耗时的问题。

3、性能影响

* `levledb`内存占用：未得到详细数据，需要开发过程中测试。
* `leveldb`对节点同步或者重放区块的影响：未得到信息数据，需要开发过程中测试。
