### ISSUE TITLE
how to register accout with public key  created on offline

### ISSUE THREAD

**Issue by bitcodernull** [gxchain/gxb-core#14]

**Comment by zhuliting** [comment]
@bitcodernull 
account with a lifetime membership can register account with public key, using cli_wallet


example : 
```
>>> register_account "newaccount" "public active key" "public owner key" "1.3.11" "1.3.11" 10 true
```

**Comment by bitcodernull** [comment]
thanks
i try it

**Comment by bitcodernull** [comment]
I am not lifetime membership
if i want to register accout with public key created on offline, how to do it

**Comment by zhuliting** [comment]
@bitcodernull  
you can ask  a lifetime member for help, or upgrade your account

**Comment by zhuliting** [comment]
solved.
