### ISSUE TITLE
gxx编译优化

### ISSUE THREAD

**Issue by secp256** [gxchain/gxb-core#146]
去除合约中未包含的引用，减少编译文件大小，降低开发者部署智能合约的费用

**Comment by RootkitKiller** [comment]
添加一些gxx编译工具优化方案，以下为语法上的优化

属性说明符：
1、使用属性说明符[[graphene::action]] 代替 // @abi action
2、使用属性说明符[[graphene::table]] 代替// @abi table name i64
3、添加属性说明符[[graphene::contract]]

宏相关：
1、添加头文件，使用宏 ACTION / TABLE / CONTRACT 代替属性说明符
2、去掉GRAPHENE_ABI宏 和 GRAPHENE_SERIALIZE宏（兼容去掉和不去掉两个版本）

其他优化方案建议可以继续讨论

**Comment by bijianing97** [comment]
属性说明符：
4、使用属性说明符[[graphene::payable]] 代替 // @abi payable
