### ISSUE TITLE
增加智能合约收费方案testcase

### ISSUE THREAD

**Issue by lanhaoxiang** [gxchain/gxb-core#148]
1. 同一块内存占用，从fee_payer A变更为fee_payer B

2. 跨合约调用的手续费支付方权限控制，不相关调用方不能作为手续费支付对象

其他：待补充

**Comment by RootkitKiller** [comment]
3. 账户A --->合约B--->合约C，对于合约C，(emplace / modify ) payer可以为原始调用者为A，调用者为B，当前合约C。当合约C-->合约B，构成循环调用的时候，验证原始调用者是否会被修改，以及循环调用层数限制是否有效。（权限相关）

4. 测试账户A ---> 合约B --->合约C --->合约D，非循环调用，(emplace/modify) payer依次设置为相关账户（ABCD可以成功，其他账户失败）。（权限相关）

5. emplace设置的payer为A，在modify时修改payer为B，验证是否有效，该次涉及的内存返还A账户的消耗，变更为B账户来支付。（手续费相关）

**Comment by RootkitKiller** [comment]
6. erase删除内存后的返还测试，验证返还的账户是否为该内存对应的payer

**Comment by RootkitKiller** [comment]
7. 合约中emplace的payer设置为账户A，更新合约使emplace的payer为账户B，则删除之前的对象，退还的手续费应该到A账户

**Comment by RootkitKiller** [comment]
## 1 基本合约，payer权限测试(emplace/modify)
- `payer为0` 合约账户支付手续费（需要保证有足够的资产）
- `payer为_self` 合约账户支付手续费（需要保证有足够的资产）
- `payer为sender` 调用者支付手续费 
- `payer为other` 失败，payer没有权限设置为非关联账户


**测试过程**: 依次修改emplace/modify 的payer为`0/_self/sender/other`
**成功条件**: `0/_self/sender`权限通过，`other`报没有权限错误

## 2 基本合约，手续费返还测试(erase)

每个table对象，都保存了该对象对应的payer
**测试过程**: 删除指定的对象（payer依次为`0/_self/sender`）
**成功条件**: 返还手续费到对应的账户

## 3 基本合约，变更payer之后，对手续费返还的影响

### 3.1 合约内部变更payer

**测试过程-1**: 对于table中的一个对象，在emplace时，指定了付费的payer为A。可以在modify时，修改payer为B。
**成功条件-1**: 返还A的手续费，并由B来支付。
**测试过程-2**: 使用erase方法删除对象
**成功条件-2**: 手续费返还给B

### 3.2 更新合约变更payer

更新合约之后，合约中`emplace/modify`的payer由A变成B，并不会影响内存中已存在对象的payer。

**测试过程**: 更新合约，变更`emplace/modify`的payer为B，删除已存在的对象
**成功条件**: 手续费返还依然为A

## 4 内联合约，payer权限测试（emplace/modify）
- `payer为0` 合约账户支付手续费（需要保证有足够的资产）
- `payer为_self` 合约账户支付手续费（需要保证有足够的资产）
- `payer为相关调用者` 调用链上的关联账户
- `payer为非相关调用者` 非调用链上的账户

测试`账户A ---> 合约B --->合约C --->合约D`，`(emplace/modify) payer`依次设置为相关账户（ABCD可以成功，其他账户失败）

**测试过程**: 依次修改emplace/modify 的payer为`0/_self/sender/关联账户/非关联账户`
**成功条件**: `0/_self/关联账户`权限通过，`非关联账户`报没有权限错误

对于`用户A-->合约B-->合约C-->合约D`的调用关系，合约D的payer设置如下
- 关联账户：A、B、C、D 均此调用关系的关联账户，合约D中的paery可以为A、B、C、D
- 非关联账户：除A、B、C、D之外的账户，其他账户为非关联账户

## 5 内联合约，循环调用（原始调用者api测试，调用层数测试）
  账户A --->合约B--->合约C，对于合约C，(emplace / modify ) payer可以为原始调用者为A，调用者为B，当前合约C。当合约C-->合约B，构成循环调用的时候，验证原始调用者是否会被修改，以及循环调用层数限制是否有效。
  
**测试过程**: 构造一个循环调用，测试原始调用者是否会变更（`get_trx_original`函数），验证层数限制是否有效
**成功条件**: 原始调用者不会变更，层数限制有效（会中断执行，抛出层数超过限制异常）

## 6 内联合约，手续费返还测试（erase）

存在一个调用链`账户A ---> 合约B --->合约C --->合约D`,内存对象的payer分别为A、B、C、D，删除对象之后手续费返还到对应的账户

**测试过程**: 构造调用链关系，并创建几种不同payer的对象，并调用erase接口删除
**成功条件**: 删除之后手续费返还到对应的payer账户

## 7 内联合约，变更payer之后，对手续费返还的影响

### 7.1 合约内部变更payer

**测试过程-1**: 对于table中的一个对象，在emplace时，指定了付费的payer为A。可以在modify时，修改payer为B。
**成功条件-1**: 返还A的手续费，并由B来支付。
**测试过程-2**: 使用erase方法删除对象
**成功条件-2**: 手续费返还给B

### 7.2 更新合约变更payer

更新合约之后，合约中`emplace/modify`的payer由A变成B，并不会影响内存中已存在对象的payer。

**测试过程**: 更新合约，变更`emplace/modify`的payer为B，删除已存在的对象
**成功条件**: 手续费返还依然为A

**Comment by lanhaoxiang** [comment]
Good job
