### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by fjh1997** [gxchain/gxb-core#15]
after I type "make" in the command line,It begin to build and link,but at 83%,the errors occur,and build failed,the detail is below:
-------------------------------------------------------------------------------------------------
market.cpp:(.text+0x16c3)：对‘fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)’未定义的引用
/home/fjh1997/桌面/gxb-core/build/libraries/chain/libgraphene_chain.a(proposal.cpp.o)：在函数‘graphene::chain::proposal_create_operation::validate() const’中：
proposal.cpp:(.text+0x1ff)：对‘fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)’未定义的引用
/home/fjh1997/桌面/gxb-core/build/libraries/chain/libgraphene_chain.a(proposal.cpp.o)：在函数‘graphene::chain::proposal_update_operation::validate() const’中：
proposal.cpp:(.text+0x5a9)：对‘fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)’未定义的引用
proposal.cpp:(.text+0x704)：对‘fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)’未定义的引用
proposal.cpp:(.text+0x875)：对‘fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)’未定义的引用
/home/fjh1997/桌面/gxb-core/build/libraries/chain/libgraphene_chain.a(proposal.cpp.o):proposal.cpp:(.text+0x9b6): 跟着更多未定义的参考到 fc::log_message::log_message(fc::log_context, std::string, fc::variant_object)
collect2: error: ld returned 1 exit status
libraries/egenesis/CMakeFiles/embed_genesis.dir/build.make:130: recipe for target 'libraries/egenesis/embed_genesis' failed
make[2]: *** [libraries/egenesis/embed_genesis] Error 1
CMakeFiles/Makefile2:863: recipe for target 'libraries/egenesis/CMakeFiles/embed_genesis.dir/all' failed
make[1]: *** [libraries/egenesis/CMakeFiles/embed_genesis.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
-------------------------------------------------------------------------------------------------------------------------
what's the matter???

**Comment by tututt** [comment]
What is your operating system？And check your submodule whether “master” or not？

**Comment by fjh1997** [comment]
my operating system is ubuntu 16.04,and how to check the version of submodule?the submodule is below,and I don't know if it is "master".
2ca9a76a7bc2c8617839e3c6eb24db899b6ac4b8 docs (2ca9a76)
 b9af764c56107fbaff6a065ebbd332f74002d540 libraries/fc (b9af764)

**Comment by fjh1997** [comment]
formally I'm ubuntu 16.04 LTS,now I change to 14.04,the same errors occur,I don't know how to check the submodule whether “master” or not,the hash value of submodule is below:
fjh1997@fjh1997-UX303UB:~/桌面/gxb-core$ git submodule
 2ca9a76a7bc2c8617839e3c6eb24db899b6ac4b8 docs (2ca9a76)
 b9af764c56107fbaff6a065ebbd332f74002d540 libraries/fc (b9af764)

**Comment by tututt** [comment]
update libraries/fc:e6ec33903b62c829ecd6a14bdca192b254fee79f,and try again

**Comment by fjh1997** [comment]
I change the submodule,errors still occur:
fjh1997@fjh1997-UX303UB:~/桌面/gxb-core$ git submodule
+67a1e807e3f24f73949a0714e7953c12271f210f docs (heads/master)
 e6ec33903b62c829ecd6a14bdca192b254fee79f libraries/fc (heads/master)

**Comment by zhuliting** [comment]
@fjh1997 

please follow the instructions:
`
cd gxb-core
git submodule update --init --recursive
git pull
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_INCLUDE_DIR=/usr/include/openssl -DOPENSSL_LIBRARIES=/usr/lib/openssh -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make -j4
`

**Comment by fjh1997** [comment]
@zhuliting 
Thanks!succeed,and I wonder why.

**Comment by fjh1997** [comment]
@zhuliting 
However,when I running the node,it seems Initializing failed:
fjh1997@fjh1997-UX303UB:~/桌面/gxb-core/build$  ./programs/witness_node/witness_node --rpc-endpoint="127.0.0.1:8090"
206374ms th_a       main.cpp:152                  main                 ] Writing new config file at /home/fjh1997/桌面/gxb-core/build/witness_node_data_dir/config.ini
206374ms th_a       data_transaction_plugin.cpp:49 plugin_initialize    ] data_transaction plugin: plugin_initialize() begin
206374ms th_a       data_transaction_plugin.cpp:54 plugin_initialize    ] data_transaction plugin: plugin_initialize() end
206374ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
206374ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: GXC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
206374ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
206374ms th_a       db_management.cpp:156         open                 ] Wiping object_database due to missing or wrong version
206374ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
206374ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
206374ms th_a       object_database.cpp:106       open                 ] Opening object database from /home/fjh1997/桌面/gxb-core/build/witness_node_data_dir/blockchain ...
206374ms th_a       object_database.cpp:111       open                 ] Done opening object database.
206375ms th_a       application.cpp:318           operator()           ] Initializing database...
段错误 (核心已转储)

**Comment by zhuliting** [comment]
@fjh1997

**Comment by fjh1997** [comment]
no help
---------------------------------------------------------------------------------------------------------------------------------------
fjh1997@fjh1997-UX303UB:~/桌面/gxb-core/build$  ./programs/witness_node/witness_node --rpc-endpoint="127.0.0.1:8090"
3590354ms th_a       data_transaction_plugin.cpp:49 plugin_initialize    ] data_transaction plugin: plugin_initialize() begin
3590354ms th_a       data_transaction_plugin.cpp:54 plugin_initialize    ] data_transaction plugin: plugin_initialize() end
3590354ms th_a       witness.cpp:88                plugin_initialize    ] witness plugin:  plugin_initialize() begin
3590354ms th_a       witness.cpp:99                plugin_initialize    ] Public Key: GXC6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
3590354ms th_a       witness.cpp:117               plugin_initialize    ] witness plugin:  plugin_initialize() end
3590354ms th_a       object_database.cpp:106       open                 ] Opening object database from /home/fjh1997/桌面/gxb-core/build/witness_node_data_dir/blockchain ...
3590354ms th_a       object_database.cpp:111       open                 ] Done opening object database.
3590354ms th_a       application.cpp:318           operator()           ] Initializing database...
段错误 (核心已转储)

**Comment by zhuliting** [comment]
@fjh1997 
please try the following instructions:
```
cd gxb-core && git checkout .
git pull && git checkout master
git submodule update --init --recursive
rm -rf build && mkdir -p build && cd build
cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_INCLUDE_DIR=/usr/include/openssl -DOPENSSL_LIBRARIES=/usr/lib/openssh -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make -j4
```

**Comment by fjh1997** [comment]
It works!Thank you!
@zhuliting
