### ISSUE TITLE
智能合约更新逻辑调整

### ISSUE THREAD

**Issue by zhuliting** [gxchain/gxb-core#160]
1. 不再校验code_hash和原来的是否一致，code hash一致也可以更新成功
   * 或者同时校验abi和code_hash，如果abi和code hash跟原来的完全一致，表示合约没更新
2. 手续费调整，不再按code size收费，改为按code size差值收取手续费

**Comment by RootkitKiller** [comment]
现在部署合约和更新合约的手续费不是抵押的方式，现在需要改成这种方式吗，更新合约，code变小，会返还部分费用

**Comment by zhuliting** [comment]
差价<0， RAM费用收取0，不退还。
