### ISSUE TITLE
开发合约中遇到的一些问题

### ISSUE THREAD

**Issue by zonxin** [gxchain/gxb-core#163]
### 1.搭建本地测试合约的私链应该使用哪个分支或是怎么正确的配置

我想开发一个合约, 所以我用使用 `private-net` 分支编译了一个私链, 我根据教程在配置文件中配置了多条 `witness-id`， 当运行 witness 节点的时候遇到了如下提示， 说不能重复定义配置：

> 1100404ms th_a       main.cpp:153                  main                 ] 13 N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_13property_tree10ini_parser16ini_parser_errorEEEEE: $PROJECT_PATH/data/config.ini(45): duplicate key name
$PROJECT_PATH/data/config.ini(45): duplicate key name: 
    {"what":"$PROJECT_PATH/data/config.ini(45): duplicate key name"}
    th_a  main.cpp:359 load_logging_config_from_ini_file
1100404ms th_a       main.cpp:154                  main                 ] Error parsing logging config from config file $PROJECT_PATH/data/config.ini, using default config

### 2. 超出 CPU usage limit 问题怎么解决
调用合约时经常会出现下面这个错误
> transaction exceeded the current CPU usage limit imposed on the transaction: transaction was executing for too long
即使是例子中的 helloworld

### 3. Unable to find Object 1.3.1

>  Assert Exception: maybe_found != nullptr: Unable to find Object 1.3.1
私链之前会遇到上述错误， 所以我合并了 #147 ， 这样不带资产的合约可以使用了，但是带资产的合约调用依旧有上述错误

### 4.  不同分支的 cli_wallet  有什么不同吗？

我可以使用 dev_master 编译出的 cli_wallet 链接我的私链吗？ 会有什么问题吗？

**Comment by RootkitKiller** [comment]
问题1：这个问题没事，应该是加载config.ini配置信息的时候，有多个witness_id字段报的提示。只要按配置的witness出块就可以。

问题2：这个是执行交易超时的问题，你的witness节点是在debug模式下吗，如果调试状态下，可能会造成交易超时。

问题3：这个错误是因为私链上没有1.3.1资产，使用的是1.3.0。调用合约时，附带1.3.0的资产试试

问题4：可以编译cli_wallet，不过最好是使用与witness_node程序相同版本的。由于cli_wallet工具与witness_node程序交互，使用不同的版本，可能会有某些接口不一致的问题。

**Comment by zonxin** [comment]
感谢您的回答。

对于问题2 我是在debug 模式下运行的 witness。 我在测试一下。

对于问题3， 我看了一下私链上的资产id，GXC确实是  1.3.0, 没有 1.3.1 的 资产
> unlocked >>> get_asset 1.3.0
{"id": "1.3.0", "symbol": "GXC", "precision": 5, "issuer": "1.2.3", ...}

**当我使用1.3.0 调用时依旧时上述错误( hi 已经改为payable，在testnet上测试过了)。**
> call_contract nathan hello  {"amount":10000,"asset_id":1.3.0} hi "{\"user\":\"GGG\"}" GXC true 


*** ***可能有帮助的一些信息
错误信息,：

![Screenshot from 2019-04-09 12-54-34](https://user-images.githubusercontent.com/7472899/55774674-bfd6df80-5ac8-11e9-8422-0660d0ecf1c9.png)

**更前面的调用堆栈我看过了，使用的参数确实是 1.3.0, 但是调用 index::get的时候参数就是 `1.3.1` 了**

evaluator.cpp 51 行是  `FC_CAPTURE_AND_RETHROW() ` 我没有搜到这个宏的定义，所以我不能确定时那里出错了。
```c++
   operation_result generic_evaluator::start_evaluate(transaction_evaluation_state& eval_state, const operation& op, bool apply, uint32_t billed_cpu_time_us)
   { try {
      trx_state   = &eval_state;
      //check_required_authorities(op);
      auto result = evaluate( op );

      if (apply) result = this->apply(op, billed_cpu_time_us);
      return result;
   } FC_CAPTURE_AND_RETHROW() }
```

**Comment by RootkitKiller** [comment]
好的，谢谢你提供的信息，我也去测试一下找找问题

**Comment by RootkitKiller** [comment]
@zonxin 需要修改一个地方，然后重新编译出`cli_wallet`和`witness_node`这两个程序。

修改的地方如下：
https://github.com/gxchain/gxb-core/blob/private-net/libraries/chain/contract_evaluator.cpp#L240
修改为：
`
transfer_op.fee = (d.head_block_time() > HARDFORK_1008_TIME) ? asset{0, asset_id_type(1)} : asset{0, asset_id_type(0)};`

我这里测试可以了，你可以试试看还有问题吗，测试结果：

```
unlocked >>> call_contract nathan hello0306 {"amount":100,"asset_id":"1.3.0"} hi "{\"user\":\"gxchain\"}" GXC true
call_contract nathan hello0306 {"amount":100,"asset_id":"1.3.0"} hi "{\"user\":\"gxchain\"}" GXC true
{
  "ref_block_num": 674,
  "ref_block_prefix": 1471391628,
  "expiration": "2019-04-09T08:11:55",
  "operations": [[
      75,{
        "fee": {
          "amount": 100,
          "asset_id": "1.3.0"
        },
        "account": "1.2.17",
        "contract_id": "1.2.18",
        "amount": {
          "amount": 100,
          "asset_id": "1.3.0"
        },
        "method_name": "hi",
        "data": "076778636861696e",
        "extensions": []
      }
    ]
  ],
  "extensions": [],
  "signatures": [
    "2046a8da5d84b8ad5e1358ec8c696ccd3523d0a039443d66aa2817697ddbee09d872bd62bcf6ebeee33e6fd87a3669a31140a70247633944b29bec20d38cf6e09b"
  ]
}
```

**Comment by zonxin** [comment]
好的，我编译一下试试，感谢

**Comment by zonxin** [comment]
@RootkitKiller  可以了，谢谢！
