### ISSUE TITLE
RPC接口怎么通过txid获取交易信息

### ISSUE THREAD

**Issue by ViolainOt** [gxchain/gxb-core#177]
在文档中没有找到相关命令

**Comment by zhuliting** [comment]
txid反查接口目前已开发完成，尚未发布。

**Comment by ViolainOt** [comment]
> TxID添加反查接口目前已开发完成，尚未发布。

我看区块信息里面的交易信息收发人都是账户id，怎么通过这个id获取到账户地址，RPC有相应的方法吗

**Comment by zhuliting** [comment]
@ViolainOt 
https://docs.gxchain.org/zh/guide/apis.html#get-objects
