### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by qianwan** [gxchain/gxb-core#18]
**Dev env**
  1. ubuntu 14.04
  2. gcc 5.4.1
  3. boost 1.57.0
  4. cmake 2.8.12.2

**What I did**
  1. git clone https://github.com/gxchain/gxb-core.git
  2. cd gxb-core
  3. git submodule update --init --recursive
  4. git checkout master
  5. mkdir build && cd build
  6. cmake -DOPENSSL_ROOT_DIR=/usr/bin -DOPENSSL_INCLUDE_DIR=/usr/include/openssl -DOPENSSL_LIBRARIES=/usr/lib/openssh -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && make -j4

**Building errors**

[ 63%] Building CXX object libraries/fc/tests/CMakeFiles/all_tests.dir/utf8_test.cpp.o
Linking CXX executable all_tests
../libfc.a(filesystem.cpp.o): In function `_ZN5boost10filesystem4pathC4INS0_15directory_entryEEERKT_PNS_9enable_ifINS0_11path_traits11is_pathableINS_5decayIS4
_E4typeEEEvE4typeE':
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::s
tring&)'
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::s
tring&)'
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::s
tring&)'
collect2: error: ld returned 1 exit status
make[2]: *** [libraries/fc/tests/all_tests] Error 1
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by zhuliting** [comment]
lib fc build failed. 
please install boost with script/boost_install.sh of gxb-core.
or check whether you have complete installed the  boost libraries from build log:

```
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.1f") 
** websocketpp
```
