### ISSUE TITLE
testnet 合约更新有问题

### ISSUE THREAD

**Issue by zonxin** [gxchain/gxb-core#189]
**合约部署，然后更新之后合约就会调用失败**

**To Reproduce**
1. 部署一下代码：
```c++
#include <graphenelib/asset.h>
#include <graphenelib/contract.hpp>
#include <graphenelib/dispatcher.hpp>
#include <graphenelib/print.hpp>
#include <graphenelib/types.h>

using namespace graphene;

class helloworld : public contract
{
  public:
    helloworld(uint64_t id)
        : contract(id)
    {
    }

    /// @abi action
    void withdraw(int64_t amount)
    {
        withdraw_asset(_self, 3200, 1, amount);
    }
};

GRAPHENE_ABI(helloworld, (withdraw))

```
合约调用没有问题。

**Expected behavior**
修改`withdraw_asset`中的`3200` 为另一个值，比如`3105`, 重新部署合约。 此时再调用合约，则出现 `assertion failure with message: read` 错误。 （这个错误一般是修改了合约中的表之后，使用新的表结构读取旧的存储出现的错误）。

**测试环境**
gxc-smart-contract-ide v1.1.0 以及 cli_wallet v1.0.190521 @ Ubuntu 16.04 LTS 64-bit
用 cli_wallet v1.0.190321 可以部署，但是不能更新，更新会出现`insufficient fee: Insufficient Fee Paid` 错误（此时余额充足）

**其他**
其他一些不正常的现象表明（详细的我还要再验证一下）， 可能是更新合约时， 节点间同步合约代码出现了问题， 导致了 #187 。

**Comment by RootkitKiller** [comment]
好的，谢谢您提供的信息，"修改合约更新逻辑"是近期测试网更新的功能，我去跟踪一下这个问题。

有两个问题需要再确定一下，

第一个问题：修改了3200为3105后，重新部署为一个新的合约，再调用新合约这个action触发的这个问题吗。 还是更新？

第二个问题：使用cli_wallet v1.0.190521 这个客户端，更新合约会报金额不足的错误吗，连接的接入点是哪个节点

**Comment by zonxin** [comment]
第一个问题， **部署为新的不报错，但是更新会报错**， 只要是`update_contract` 即使从`3105`改成`3200`也会报错更新成功之后也会报错。 
**错误的报错和这个action之外的代码似乎也有点儿关系**。 为了确定 #185 里面说的那个问题，我还部署了另外一个有点复杂的合约，也是`withdraw` 只有一句`withdraw_asset`。 具体现象错误现象不是每次都能复现，我还没总结出规律，这个如果问题一直没有解决的话，后面我再整理一下。

第二个问题，接入点是 `cli_wallet -swss://testnet.gxchain.org --chain-id c2af3...`
+ 版本1： 合约可以更新成功，不会报金额不足的错误。 但是更新之后调用会出错。 `cli_wallet v1.0.190521` 和 IDE v1.1.0  这两个问题我都试过
+ 版本2： 可以时候这个版本部署合约，但是使用这个版本更新合约会出现金额不足的错误。 具体版本是
`cli_wallet v1.0.190321`。 IDE 的前一个版本没有试。

另， gxx 的版本号怎么看以及在那个库里？ 
使用 cli_wallet 中部署的合约时我自己编译的 gxx 某个  tag， 我都忘记了。

**Comment by RootkitKiller** [comment]
测试网已经更新了版本，并修复了智能合约更新的逻辑。
[testnet-1.0.190613](https://github.com/gxchain/gxb-core/releases/tag/testnet-1.0.190613)
