### ISSUE TITLE
Ipfs node address? 

### ISSUE THREAD

**Issue by wellttllew** [gxchain/gxb-core#19]
你好，我在你们的白皮书里看到：

> 个人信息数据是加密存储在 ipfs 上面的

我想要自己去访问一下这些加密的文件，但我遇到两个问题：

1. 首先是你们存储这些文件的 ipfs 地址是哪个呢？ 另外可否告知一下目录结构  ？ 

2. 你们提到使用非对称加密，那这里的 private key 具体是指哪个呢？

**Comment by lanhaoxiang** [comment]
近期布洛克城开放的功能里面会有详细介绍，敬请关注
