### ISSUE TITLE
Testnet 调用合约

### ISSUE THREAD

**Issue by Alan52** [gxchain/gxb-core#192]
在测试网络中使用GXCWallet调用合约，抛出异常。偶现

异常：
type: "un_def_error", message: "Cannot destructure property `code` of 'undefined' or 'null'.", code: 433, isError: true, originalError: TypeError: Cannot destructure property `code` of 'undefined' or 'null'.

**Comment by Alan52** [comment]
GXC Wallet 版本信息：0.0.2

**Comment by RootkitKiller** [comment]
已解决 #190
