### ISSUE TITLE
每次重启都会重新Replaying blocks

### ISSUE THREAD

**Issue by callac** [gxchain/gxb-core#199]
Replaying blocks, [by size: 5.92233% 2630930320 of 44423914409] [by num: 14.4898% 3314000 of 22871228]
Replaying blocks, [by size: 5.92889% 2633846287 of 44423914409] [by num: 14.4942% 3315000 of 22871228]
Replaying blocks, [by size: 5.93846% 2638096408 of 44423914409] [by num: 14.4986% 3316000 of 22871228]
Replaying blocks, [by size: 5.94865% 2642624467 of 44423914409] [by num: 14.5029% 3317000 of 22871228]
Replaying blocks, [by size: 5.95909% 2647261882 of 44423914409] [by num: 14.5073% 3318000 of 22871228]
Replaying blocks, [by size: 5.96942% 2651851152 of 44423914409] [by num: 14.5117% 3319000 of 22871228]
Replaying blocks, [by size: 5.97969% 2656412229 of 44423914409] [by num: 14.5161% 3320000 of 22871228]

KiB Mem : 16431684 total,   172992 free,  4017188 used, 12241504 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 12041800 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 8709 root      20   0  128912  69188  23552 R  90.0  0.4   9:59.66 witness_node

而且CPU还占用特别高

有什么解决方案吗？

**Comment by callac** [comment]
版本  gxb_1.0.190318-ubuntu-14.04.tar.gz

**Comment by RootkitKiller** [comment]
一般启动时重放区块，是因为witness_node退出时状态数据库被破坏导致的，退出时使用`kill -s SIGINT $(pgrep witness_node)`。并且重新启动witness_node程序时，如果不想重放区块，请不要添加`--replay-block `参数。

重放区块时，需要重新执行所有交易，会造成CPU占用，建议CPU最低四核以上，如果对重放时间没有要求，重放时可以去掉 `--fast-replay`参数，但是会延迟重放的时间。
