### ISSUE TITLE
尝试弄懂 operation 的含义 ，发现了安全问题？ 

### ISSUE THREAD

**Issue by wellttllew** [gxchain/gxb-core#20]
你好，今天偶然看到你们的项目，去看了一下你们的 blockchain explorer .    
我注意到你们在 `graphene` 的基础上添加很多 `operations`.  

1. 可否在之后给出这些 `operations` 的具体文档呢？ 

2. 我有注意到，你们新添加的一些比较重要的 `operations` 中的 validate 是没有实现的， 这意味着这个 tx 完全没有验证？？！！  还是我的理解有问题呢？

**Comment by zhuliting** [comment]
tx的验证放在了do_evaludate里，安全上没有问题。

**Comment by zhuliting** [comment]
@wellttllew 欢迎加入开发者qq群 627798113

**Comment by wellttllew** [comment]
@zhuliting  谢谢答复, 刚刚看了一下， sorry， 是我误会了。 我理解成 operation 的 validate 是实现 tx 的验证了， 我以为连 tx 的 signature 都不做验证。
