### ISSUE TITLE
默认添加txid反查插件，不再使用可选插件配置的方式[WIP]

### ISSUE THREAD

**Issue by RootkitKiller** [gxchain/gxb-core#204]
问题描述：txid反查插件在GXChain网络中，使用较频繁，后续将txid反查插件添加为默认插件。

解决方式：默认安装leveldb依赖库并编译txid反查插件代码。

**Comment by bijianing97** [comment]
Query_txid plugin is off normal state,  you can start it when you compile , using `cmake-DLOAD_TXID_PLUGIN=ON`
