### ISSUE TITLE
docker/start.sh中elif缺少then

### ISSUE THREAD

**Issue by haosuwei** [gxchain/gxb-core#21]
https://github.com/gxchain/gxb-core/blob/9cf2455494b9603bc63d26077abf3fe13db8d47c/docker/start.sh#L54

这里elif后面也需要跟;then
我在ubuntu14.04环境中，docker-ce 17.12中验证报错，导致容器无法启动

**Comment by zhuliting** [comment]
@haosuwei Thank you!
