### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by Justinwone** [gxchain/gxb-core#22]
we are using ubuntu 14.4.5 for building, we almost build successfully, but got error as following, do you have any idea about this build issue? thanks!

collect2: error: ld returned 1 exit status
make[2]: *** [libraries/egenesis/embed_genesis] Error 1
make[1]: *** [libraries/egenesis/CMakeFiles/embed_genesis.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object libraries/wallet/CMakeFiles/graphene_wallet.dir/api_documentation.cpp.o

**Comment by zhuliting** [comment]
@liliyongleo 
@Justinwone 

use boost 1.65.0
