### ISSUE TITLE
Hi, I'm wondering whether the test net of gxchain has been stopped?

### ISSUE THREAD

**Issue by lecht** [gxchain/gxb-core#24]
After using specific command to connect to the test of gxchain, after downloading all the blocks in test net, when I use "info" command, I got "head_block_num": 3479962, and  "head_block_age": "18 days old".
And still it won't increase, who can give me some suggestion on how to resolve this problem, thanks a lot!

**Comment by zhuliting** [comment]
@lecht 

I have checked the log of witness_node from testnet, it works well. Could you please show your latest witness_node.log ？
like this:
```
2018-05-07T06:56:45 th_a:Witness Block Production block_production_loo ] Generated block #3930108 with timestamp 2018-05-07T06:56:45 at time 2018-05-07T06:56:45			witness.cpp:186

```

**Comment by lecht** [comment]
@zhuliting 
Thanks a lot for your advice, finally I got my gxchain settings right. 
xiexie

**Comment by lecht** [comment]
Another question, I recognized that the fee in a transfer action, sometimes the asset ID of the transfer fee is 1.3.1, and sometimes it is 1.3.0, as in [https://github.com/gxchain/gxb-core/wiki/for_exchanges](url) shows, I'm wondering if this exists all the time, or just in the example case.
Thanks again.

**Comment by zhuliting** [comment]
@lecht 
default 1.3.0
