### ISSUE TITLE
erro While importing wallet

### ISSUE THREAD

**Issue by mcb345** [gxchain/gxb-core#27]
I am doing
import_key some_name some_key
but the wallet_cli return
`rec && rec->name == account_name_or_id:`
    `{}`
  ` th_a  wallet.cpp:602 get_account`

Am i missing anything here ? I tried putting quotes to the string too, no luck
My syncing hasnt finished tho, do I need to wait the node finish syncing first ? As the wallet I created from the online wallet just recently (from wallet.gxb.io)

**Comment by zhuliting** [comment]
@mcb345 
account_name can't be found, as the head block time of your node is earlier than the time which your account is created. please retry after the node finish syncing all the blocks.
