### ISSUE TITLE
can't install libstdc++-8-dev

### ISSUE THREAD

**Issue by zoujinbin** [gxchain/gxb-core#34]
I tried to install libstdc++-8-dev dependency via apt-get on Ubuntu 14.04.5 LTS,but I got an error as follows.Do you have any idea about this issue? thanks!

root@localhost:~# apt-get install libstdc++-8-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libstdc++-8-dev
E: Couldn't find any package by regex 'libstdc++-8-dev'

**Comment by zhuliting** [comment]
libstdc++-8-dev is not required, please install libstdc++-dev

**Comment by zhuliting** [comment]
```
apt-get install libstdc++6
```


@zoujinbin

**Comment by zoujinbin** [comment]
I have already installed libstdc++-4.8-dev and libstdc++6 on Ubuntu 14.04.5 LTS,but still got the same error like above.Is the libstdc++-8-dev required?How can I install it?

root@localhost:~/gxb-core# apt-get install libstdc++-4.8-dev  libstdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libstdc++-4.8-dev is already the newest version.
libstdc++6 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 146 not upgraded.

**Comment by zhuliting** [comment]
@zoujinbin 

please try the following instructions, and then recompile
```
add-apt-repository ppa:ubuntu-toolchain-r/test
apt-get update
apt-get install libstdc++-8-dev
```

**Comment by zoujinbin** [comment]
Thanks! It works.
