### ISSUE TITLE
Error: No available formula with the name "cmake@3.11" 

### ISSUE THREAD

**Issue by arrfu** [gxchain/gxb-core#37]
brew install cmake@3.11 openssl wget git openssl autoconf automake doxygen libtool llvm@4

Error: No available formula with the name "cmake@3.11" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

你好，执行第二步 Install dependencies 时报了这个错误，网上找不到解决方式；请问下有解决办法吗？
非常感谢。

**Comment by zhuliting** [comment]
```
 brew install cmake
```

**Comment by arrfu** [comment]
你好，非常感谢您的解答！
但是执行了你的命令后，发现仍然报这个错误。不知道为何？

具体执行日志如下：

arrfudeiMac:~ arrfu$ brew remove cmake
Uninstalling /usr/local/Cellar/cmake/3.12.0... (2,415 files, 33.6MB)

arrfudeiMac:~ arrfu$ brew install cmake
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.12.0.high_sierra.bo
Already downloaded: /Users/arrfu/Library/Caches/Homebrew/cmake-3.12.0.high_sierra.bottle.tar.gz
==> Pouring cmake-3.12.0.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.12.0: 2,415 files, 33.6MB

arrfudeiMac:~ arrfu$ brew install cmake@3.11 openssl wget git openssl autoconf automake doxygen libtool llvm@4
Error: No available formula with the name "cmake@3.11" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

请问下有解决办法吗？
非常感谢。

**Comment by zhuliting** [comment]
@arrfu  cmake 3.11及以上版本就行，不需要安装cmake@3.11了

**Comment by arrfu** [comment]
谢谢，那就继续往第3步执行命令，发现又报错误了。。。
arrfudeiMac:~ arrfu$ wget https://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz/download -O  boost_1_67_0.tar.gz
-bash: wget: command not found

尴尬😓，请问下有解决办法吗？
非常感谢。

**Comment by lanhaoxiang** [comment]
wget: command not found

**Comment by zhuliting** [comment]
@arrfu 编译文档更新了, 从头开始试一下。
cmake@3.11不需要安装，因为你当前的系统上已经有最新的cmake了，但文档中的其它依赖还是需要安装的。

**Comment by liukunyu** [comment]
wget can install by command : brew install wget
