### ISSUE TITLE
Support inter-contract call 

### ISSUE THREAD

**Issue by zhuliting** [gxchain/gxb-core#90]
design : https://github.com/gxchain/gxips/blob/master/gxip-002/README-CN.md

**Comment by liukunyu** [comment]
### 返还手续费
- 当前调用者对ram付费
- 返还ram费用给当前调用者，不管对应的内存是谁付费都返还给当前调用者
- 新增数据库表account_id | ram_usage_bytes | fee_sum
- 每次调用根据ram_delta扣费/返还手续费
- 需要考虑ram的费率有调整费用如何返还问题(按照当前费率返还，直到数据库记录的ram费用都返还完毕为止

**Comment by liukunyu** [comment]
关于手续费
每个账号创建一个ram_usage对象
ram_usage{
account_id_type     uint64_t
ram_usage              int64_t
ram_fee                   int64_t
}
每个对象占用18字节内存，200w用户占用2000000*18/1024/1024 = 34.33m内存，加上索引字段预计不会超过50m内存。

- 为ram付费的时候指定payer，控制好权限只能是调用者或者合约本身
- 当payer占用了内存就扣除余额，并累加在ram_usage对象
- 当payer释放了内存做反向操作
- 这样可以做到免费，也可以在返还费用的时候扣除一定的比例作为矿工费（全局参数）
- 每个用户可以知道自己用了多少内存，花了多少费用
